### ISSUE TITLE
Mobile Meta Tag

### ISSUE THREAD

**Issue by Mikeysax** [derekbets/Splurty#1]
On mobile things don't look as good as they could be.
One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.
Let me know in the comments once you figured that step out :)

**Comment by derekbets** [comment]
Hey Michael....In the <head> section of the application.html.erb file, I added...

<meta name="viewport" content="width=device-width, initial-scale=1">

It seems to have improved the mobile view. Please let me know if there is anything else I am missing. 

Thanks
Derek

**Comment by Mikeysax** [comment]
:+1:
